- ketone/optimizer.py
- ketone/topology.py
> Enable onnx optimizer in keras converter

- ketone/common/utils.py
- ketone/main.py
- ketone/parser.py
- ketone/topology.py
- tests/test_layers.py
Then the converter would add transpose for channel_first_inputs, which is more convenient for users.
> Add channel_first_inputs to convert_keras interface

- .azure-pipelines/linux-conda-CI.yml
- .azure-pipelines/win32-conda-CI.yml
- keras2onnx/common/onnx_ops.py
- keras2onnx/ke2onnx/bidirectional.py
* Update to ONNX v1.4.1 in CI Build scripts in accordance with opset 9 changes
* Fix apply_upsample inputs for opset 9 input check
> Update ONNX version to 1.4.1 in CI Build

- keras2onnx/common/onnx_ops.py
As title. No new content changes, only restructuring current ops -- proposed as new PR from discussion in #31.
Additional benefit of being easier to merge common code later on.
> Alphabetize common onnx ops for searchability

- keras2onnx/wrapper.py
In https://github.com/onnx/tensorflow-onnx/pull/384/files
There is a breaking change (remove g.update_proto()) then our code breaks. Add it from our side.
> Add tf2onnx graph update_proto

- keras2onnx/common/onnx_ops.py
onnx upsample no longer exists in opset 10, need update accordingly. Now it tests successfully with our application model.
> Convert upsample using Resize op in opset 10

- README.md
> Update README to reflect Python 3.7 CI testing

- keras2onnx/ke2onnx/dot.py
- keras2onnx/ke2onnx/gru.py
- keras2onnx/ke2onnx/lstm.py
- keras2onnx/ke2onnx/main.py
- keras2onnx/parser.py
- keras2onnx/topology.py
- keras2onnx/wrapper.py
> Enable the dynamic batch size for the converted model and some fixings.

- keras2onnx/ke2onnx/upsample.py
- tests/test_layers.py
Push through changes from #71.
> Add Interpolation attribute to Keras UpSampling2D

- keras2onnx/common/onnx_ops.py
This is already tested in the private branch. Will add more tests later.
> Add OnnxOperatorBuilder

- README.md
+ state compatibility with TF version 1.13.1
+ add CI status badges for tf.keras testing
> Add tf.keras versioning documentation + CI status badges

- keras2onnx/ke2onnx/bidirectional.py
- tests/test_layers.py
Also move around some code because it is only needed for the case of dynamic shape.
> Fix return_sequences=False for bidirectional

- applications/mask_rcnn/mask_rcnn.py
- applications/yolov3/yolov3.py
- keras2onnx/_builtin.py
- keras2onnx/parser.py
- keras2onnx/wrapper.py
simplify the logic and clean up some unnecessary code.
> update the yolo-v3 conversion code.

- keras2onnx/_builtin.py
- tests/test_layers.py
May add unit test for scatter_nd later.
> Convert tf.greater_equal, less_equal, scatter_nd via keras _builtin

- keras2onnx/_builtin.py
- tests/test_layers.py
len(nodes_to_keep) = 14 for tf.nn.softmax(x, axis=1), so we increase _MAX_FOLDING_NODE_NUMBER to 15.
> Add tf.softmax to unit test

- README.md
> Fixing pip install path in README

- keras2onnx/_builtin.py
- keras2onnx/ke2onnx/activation.py
- keras2onnx/ke2onnx/common.py
- tests/test_layers.py
The [issue](https://github.com/onnx/keras-onnx/issues/505) mentions it needs additional handling for input, which is different from our UT. Add the case here, will ask the issue owner for UT.
> Handle different input cases for tf.nn.relu6 support

- keras2onnx/ke2onnx/activation.py
- keras2onnx/ke2onnx/conv.py
- tests/test_layers.py
Need check in onnxconverter-common [change](https://github.com/microsoft/onnxconverter-common/pull/117) first.
> Support tf.nn.leaky_relu and fix advanced_activations

- tutorial/TensorFlow_Keras_MNIST.ipynb
example based on mnist dataset and a small custom model.
This example closes #493.
> including additional keras2onnx example

- applications/nightly_build/test_yolov3.py
- applications/yolov3/yolov3.py
Need check-in onnxconverter-common [PR](https://github.com/microsoft/onnxconverter-common/pull/123) first.
> Rewrite yolov3 conversion by Graph API

- keras2onnx/ke2onnx/main.py
- tests/test_layers.py
This is to fix the [issue](https://github.com/onnx/keras-onnx/issues/526). Need specify input shape in the model.
> Handle keras.layer.recurrent.GRU, LSTM, SimpleRNN

- keras2onnx/_builtin.py
- keras2onnx/_consts.py
- tests/test_layers.py
Reverse V2 is not an ONNX operator, so it is translated into Reverse Sequence and other set of valid ONNX operators.
> Add support for ReverseV2 operator

- keras2onnx/ke2onnx/simplernn.py
Extremely minimal PR that allows softsign activations in recurrent layers. Please let me know what tests, if any, need to be added.
> Allow softsign in recurrent layers

- tests/test_layers.py
An example for issue [here](https://github.com/onnx/keras-onnx/issues/555), tested the original model successfully, this UT makes a little simplification but not change result.
> Add a conv2d_transpose UT

- .azure-pipelines/linux-CI-keras-applications-nightly.yml
- .azure-pipelines/linux-conda-CI-tf-keras.yml
- .azure-pipelines/linux-conda-CI.yml
- .azure-pipelines/win32-CI-keras-applications-nightly.yml
- .azure-pipelines/win32-conda-CI-tf-keras.yml
- .azure-pipelines/win32-conda-CI.yml
- tests/test_layers.py
- tests/test_subclassing.py
tensorflow 2.3 issue will be resolved in another PR.
> Fixed all dependency version for CI pipeline

- applications/nightly_build/test_crnn.py
- applications/nightly_build/test_nbeats.py
- applications/nightly_build/test_se_densenet.py
- applications/nightly_build/test_se_inc_resnet.py
The model 20200810 [PR](https://github.com/onnx/keras-onnx/pull/593) has bugs for python 3.5 nightly build. This PR fixes them.
> Fix models 20200810 for python 3.5 nightly build

- keras2onnx/_builtin.py
- keras2onnx/_consts.py
- tests/test_layers.py
This change enables "TensorScatterUpdate" operator conversion into ONNX "ScatterND" operator.
> Add TensorScatterUpdate conversion

- applications/nightly_build/test_deep_speaker.py
Only python 3.5 nightly build fails due to this issue.
> Fix string for model 20200825 in python 3.5 build

- applications/nightly_build/test_deep_speech.py
- applications/nightly_build/test_name_entity_recognition.py
- keras2onnx/_builtin.py
- keras2onnx/ke2onnx/simplernn.py
- keras2onnx/parser.py
Through this change, we converted 3 more keras models:
one from [repo](https://github.com/kamalkraj/Named-Entity-Recognition-with-Bidirectional-LSTM-CNNs/), the other two from [repo](https://github.com/rolczynski/Automatic-Speech-Recognition)
> Support TimeDistributed dynamic input shape and more Bidirectional merge_modes

- applications/nightly_build/test_segnet_2.py
- keras2onnx/_builtin.py
- keras2onnx/_consts.py
It supports the segnet model [here](https://github.com/ykamikawa/tf-keras-SegNet)
> Support tf op MaxPoolWithArgmax conversion

- applications/nightly_build/test_music_generation.py
- keras2onnx/ke2onnx/gru.py
- keras2onnx/ke2onnx/lstm.py
- keras2onnx/ke2onnx/main.py
- keras2onnx/ke2onnx/simplernn.py
This PR fixes the music generation model conversion [here](https://github.com/calclavia/DeepJ).
> Extract TimeDistributed LSTM input/output shapes when op does not have those

- applications/nightly_build/test_resnext.py
Like what we did in previous PR for ResNext, SEResNext also need expand the loop, which is keras source code change. Then it works.
> Add SEResNext to nightly build

- keras2onnx/ke2onnx/activation.py
- keras2onnx/parser.py
- tests/test_layers.py
Take customized GELU as an example.
> Support custom activations in Activation layer

- keras2onnx/_builtin.py
Per the [issue](https://github.com/onnx/keras-onnx/issues/640). Our last fix has no UT so didn't catch this.
> Add [] to delta.name in _make_range_non_const

- .azure-pipelines/linux-CI-keras-applications-nightly.yml
- .azure-pipelines/linux-conda-CI-tf-keras.yml
- .azure-pipelines/win32-CI-keras-applications-nightly.yml
- .azure-pipelines/win32-conda-CI-tf-keras.yml
- applications/nightly_build/test_unet.py
- applications/nightly_build/test_unet_plus_plus.py
onnxruntime 1.7.0 released to pypi today. Update our tests accordingly.
> Update test for onnxruntime 1.7.0

- README.md
Signed-off-by: Guenther Schmuelling <guschmue@microsoft.com>
> stop active development notice
