onnx/keras-onnx

.azure-pipelines/linux-conda-CI.yml, .azure-pipelines/win32-conda-CI.yml, requirements.txt
As title. Adding both to the azure CI pipelines.
=> Support for ONNX 1.5, Python 3.7

keras2onnx/ke2onnx/bidirectional.py, keras2onnx/ke2onnx/lstm.py, tests/test_layers.py
The converter was not setting the value of R bias correctly during
onnx conversion.
We simply set the R biases to zero since the current conversion code
is already setting W bias to the Keras' bias value. We expect the sum
of the biases Wb + Rb to be the same as Keras' bias since Keras uses
a single bias combining both.
Changes to be committed:
modified:   keras2onnx/ke2onnx/bidirectional.py
modified:   keras2onnx/ke2onnx/lstm.py
modified:   tests/test_layers.py
=> Bug fix in forward and bi-directional lstm in handling bias

.azure-pipelines/linux-conda-CI.yml, .azure-pipelines/win32-conda-CI.yml
* coverage is slowing down CI build times, so only keep reports in the nightly builds
* update onnx version to 1.5.0 in python 3.6 builds
=> Remove coverage from CI builds, update ONNX version

README.md
•	All keras layers have been supported since opset 7. Please refer to Keras documentation for all layers. 
•	For Windows ML users, please refer to Windows ML documentation for opset chosen.
=> Update keras2onnx opset support information

keras2onnx/ke2onnx/batch_norm.py
Update batch norm list case as done in PR #117 
Add cosmetic changes to fit into code base
"Fix issue with BatchNormalisation layer having a list axis not adding the required Transpose layer when converting a NHWC model." - @fmannhardt
=> Fix for batchnorm attribute `axis` list case by adding transpose layer

.azure-pipelines/linux-CI-keras-applications-nightly.yml, .azure-pipelines/linux-conda-CI-tf-keras.yml, .azure-pipelines/linux-conda-CI.yml, .azure-pipelines/win32-CI-keras-applications-nightly.yml, .azure-pipelines/win32-conda-CI-tf-keras.yml, .azure-pipelines/win32-conda-CI.yml
+ Installing onnxconverter-common from github master in Azure CI Pipelines so changes can persist in the build without needing to publish a new package each time
Reference: https://github.com/onnx/onnxmltools/pull/320
=> Install onnxconverter-common from source in pipelines

keras2onnx/_builtin.py, tests/test_layers.py
In tf2onnx conversion, there is a check
`utils.make_sure(all(i >= 0 for i in reduce_dim)`
in class AllAny, this is not needed.
Because (1) we have negative axis (2) ReduceSum and ReduceMin supports it.
=> Add K.Any and K.All to builtin tf op conversion

keras2onnx/ke2onnx/dot.py
keras 2.2.5 released and breaks the build, let's fix it.
=> Handle input_shape when convert Dot for keras 2.2.5

.azure-pipelines/linux-CI-keras-applications-nightly.yml, .azure-pipelines/linux-conda-CI-tf-keras.yml, .azure-pipelines/linux-conda-CI.yml, .azure-pipelines/win32-CI-keras-applications-nightly.yml, .azure-pipelines/win32-conda-CI-tf-keras.yml, .azure-pipelines/win32-conda-CI.yml, README.md
tensorflow 2.0.0 is published, set to tf 1.x for CI build now.
=> Set tensorflow 1.x for CI build

keras2onnx/parser.py
In the [refactoring](https://github.com/onnx/keras-onnx/pull/267), there is a bug for `_visit_nodelist()` where `layer_key` is not passed in. It is needed because `_get_output_nodes()`  needs it. This breaks mask rcnn conversion.
This PR fixes the issue.
=> Fix _visit_nodelist() by adding layer_key into parameters

keras2onnx/ke2onnx/main.py, tests/test_layers.py
The current implementation uses an ONNX Reshape Op, which is causing an issue when converting from ONNX to TF to TFLite.
IMO, using a Flatten Op simplifies the graph's structure, and it's a widely supported Op.
=> Convert Keras Flatten Layer to ONNX Flatten Op

.azure-pipelines/linux-CI-keras-applications-nightly.yml, .azure-pipelines/win32-CI-keras-applications-nightly.yml, README.md, applications/nightly_build/test_keras_applications.py, tests/test_utils.py
1. Add keras-tcn to nightly build
2. Move tf2onnx_contrib_op_conversion before run_onnx_runtime in test_utils (so that we can use it in unit test).
=> Add keras-tcn to nightly build

.azure-pipelines/linux-CI-keras-applications-nightly.yml, .azure-pipelines/win32-CI-keras-applications-nightly.yml, applications/nightly_build/test_keras_applications.py
keras-tcn==2.9.2 breaks our nightly build, see the issue [here](https://github.com/philipperemy/keras-tcn/issues/109). Use version 2.8.3.
=> Use keras-tcn==2.8.3

.azure-pipelines/linux-CI-keras-applications-nightly.yml, .azure-pipelines/linux-conda-CI-tf-keras.yml, .azure-pipelines/linux-conda-CI.yml, .azure-pipelines/win32-CI-keras-applications-nightly.yml, .azure-pipelines/win32-conda-CI-tf-keras.yml, .azure-pipelines/win32-conda-CI.yml, applications/nightly_build/test_mask_rcnn.py
ort-nightly will do onnx<1.7.0,>=1.6.0 to restrict onnx, so we neend pin onnxruntime for build onnx < 1.6
Disable mask_rcnn test temporarily.
=> Pin onnxruntime for build in use of onnx < 1.6

keras2onnx/_parser_1x.py, keras2onnx/common/intop.py, keras2onnx/ke2onnx/main.py, tests/test_layers.py
This PR uses the actual `mask_value`, instead of assuming that it is `0.0`. This allows custom mask values to be used, as long as they can be represented as a float32 or int32 (e.g. `np.nan` works as expected).
I added `mask_value` to the  `Operator` class to be able to pass that information down. I'm not convinced this is the best form, but it seemed to be the easiest way in the short term.
=> Custom Masking value

keras2onnx/ke2onnx/gru.py, keras2onnx/ke2onnx/lstm.py, keras2onnx/ke2onnx/main.py, keras2onnx/ke2onnx/simplernn.py, tests/test_layers.py
This PR reproduces a discrepancy between the ONNX and Keras models for handling inputs that are fully masked. This occurs for RNN models that contain both a masking layer, and use a non-zero bias. When one of the input entries is fully zero (i.e. will be fully masked by the Masking layer), the RNN output is non-zero. Turning off the bias or using the default bias reproduces consistent behavior with Keras.
```
(Pdb) up
> /home/user/keras-onnx/tests/test_layers.py(1817)test_masking_bias()
-> self.assertTrue(run_onnx_runtime(onnx_model.graph.name, onnx_model, x, expected, self.model_files))
(Pdb) x
array([[[365.8103 , 107.39152, 701.68   , 615.55023, 468.88876],
[831.7788 , 680.243  , 890.5216 , 550.38116, 970.3993 ],
[134.01295, 771.0398 , 594.99915, 315.76196, 753.1429 ]],
[[  0.     , …
```
=> Masking RNN with zeros input

keras2onnx/ke2onnx/bidirectional.py, tests/test_layers.py
This PR fixes the case of a Bidirectional LSTM when used in conjunction with a Masking layer. This follows the same solution as #386. The new graph connects the masking output to a section that computes the sequence lengths, which provides proper masking for padded input. Since the GRU and SimpleRNN layers are not yet supported for the bidirectional case, this PR does not include those cases.
=> Bidirectional Masking support

keras2onnx/ke2onnx/bidirectional.py, keras2onnx/ke2onnx/gru.py, keras2onnx/ke2onnx/lstm.py, keras2onnx/ke2onnx/simplernn.py
This PR is a step towards supporting SimpleRNN and GRU in the Bidirectional layer, by moving toward a consistent API across the RNN layers. It refactors the RNN code to increase sharing, and re-uses that in the Bidirectional LSTM case. No functional changes are made -- this PR is purely a refactor.
@wenbingl, can you review these changes?
=> Refactor RNN parameter extracting

keras2onnx/ke2onnx/gru.py, keras2onnx/ke2onnx/lstm.py, keras2onnx/ke2onnx/simplernn.py, keras2onnx/parser.py, tests/test_layers.py
This PR provides support for initial states in Bidirectional SimpleRNN, GRU, and LSTM layers. It also fixes a bug where leveraging two outputs of a Keras node can cause parsing failures (see the changes in `parser.py`). Support was extended for LSTM and Bidirectional layers that have dynamic sequence lengths (`seq_length = None`), so that it now supports down to opset 5. This was previously possible in terms of the ONNX spec, but would raise an error.
=> Support initial states for Bidirectional RNN

tests/conftest.py, tests/test_cgan.py, tests/test_layers.py, tests/test_misc.py, tests/test_tf2_keras.py
This PR migrates the testing from `unittest` to `pytest`. This allows for the use of parametrized tests and fixtures, leading to more robust test coverage and easier test-code maintenance. This was motivated by my recent PRs on Bidirectional and Masking features, where I saw that many of the tests rely on nested for-loops, which are hard to filter (using `-k`) and maintain as they expand.
Goals:
This PR is still a work in progress, and will be updated. I'm interested in any suggestions or comments.
=> unittest -> pytest

tests/test_layers.py
This PR parametrizes the RNN tests to run over the RNN classes (SimpleRNN, GRU, and LSTM). This simplifies the existing test functions, and provides the ability to filter on a specific class of interest. For example, to run all of the GRU tests, you can filter on GRU:
```
$ pytest tests -k GRU -vv
===================================== test session starts =====================================
...
collected 163 items / 152 deselected / 1 skipped / 10 selected                                
tests/test_layers.py::test_GRU PASSED                                                   [  9%]
tests/test_layers.py::test_Bidirectional[GRU-True] PASSED                               [ 18%]
tests/test_layers.py::test_Bidirectional[GRU-False] PASSED                              [ 27%] …
```
=> Parametrizing RNN tests

keras2onnx/ke2onnx/embedding.py, keras2onnx/ke2onnx/lstm.py, keras2onnx/ke2onnx/simplernn.py, tests/test_layers.py
This commit makes the following changes:
1. Embedding was unnecessarily reshaping input to a rank2 tensor. This
is not required and causes model to diverge from what its actually
supposed to do.
2. Lstm was not considering time_major param. No transpose of input and
output is required if the input is already time major, i.e of shape
[ seq_len, batch_size, input_size]
3. Simplify the handling of case when return sequences is set to true.
4. Use squeeze and unsqueeze instead of reshape for dim representing
direction of lstm for simplicity.
=> Handle time_major in lstm and remove reshape from embedding

keras2onnx/_parser_tf.py, keras2onnx/parser.py
Whenever inputs and outputs have None as dim (except for batch size), after conversion they will have 0 as the dimension.
Batch size will be converted to 'N'.
input(None, None) -> input(N, 0)
With this fix even other dims will have variables like M1, M2.
input(None, None) -> input(N, M1)
=> Adjust input output sizes when any dim is None

.azure-pipelines/linux-CI-keras-applications-nightly.yml, .azure-pipelines/win32-CI-keras-applications-nightly.yml, applications/nightly_build/test_keras_applications_v2.py, keras2onnx/parser.py, tests/test_utils.py
This is from [PR](https://github.com/onnx/keras-onnx/pull/482) with changes addressing reviewer's comments.
=> Support tensorflow 2.2

keras2onnx/_builtin.py, keras2onnx/_consts.py, tests/test_layers.py
Added support for [tf.nn.depth_to_space](https://www.tensorflow.org/api_docs/python/tf/nn/depth_to_space) as a Keras lambda, mapped to the ONNX [DepthToSpace](https://github.com/onnx/onnx/blob/master/docs/Operators.md#DepthToSpace) operator.
The two added test-cases visualised with Netron:
Channels first (NCHW), channel dimension reduced from 4 to 4/(2*2) = 1, width & height dimension increased by a factor 2:
Channels last (NHWC), channel dimension reduced from 8 to 8/(2*2) = 2, width & height dimension increased by a factor 2:
Although the visualisations look correct as far as I can see, the NHWC test-case fails with the following error in the ORT:
```
onnxruntime.capi.onnxruntime_pybind11_state.Fail:
[ONNXRuntimeError] : 1 : FAIL : Node:lambda/DepthToSpace Output:lambda …
```
=> Add support for tf.nn.depth_to_space lambda

keras2onnx/_builtin.py
Slice op supports negative begin and end, so we can use negative value rather than calculating input shape (not working for dynamic shape)
=> Fix shrink_mask in _prepare_StridedSlice for dynamic input shape

.flake8, keras2onnx/_graph_cvt.py, keras2onnx/_parser_1x.py, keras2onnx/common/data_types.py, keras2onnx/common/onnx_ops.py, keras2onnx/parser.py, keras2onnx/proto/tfcompat.py, keras2onnx/topology.py
More fixings needs to op converting files.
=> try to enable flake8 checker.

keras2onnx/ke2onnx/gru.py, keras2onnx/ke2onnx/lstm.py, keras2onnx/ke2onnx/simplernn.py, tests/test_layers.py
**Description**
```
1. Adds time major handling for bidirectional for all rnns.
2. Reverse order of squeeze and transpose in lstm conversion when return seq_true:
This makes the onnx model slightly more efficent when the model
has a stack of lstms that are batch_major.
By doing squeeze first and transpose later, we get two consucutive transposes
that get eliminated by the optimizer hereby making model more efficient.
```
**Changes to be committed**
```
modified:   keras2onnx/ke2onnx/gru.py
modified:   keras2onnx/ke2onnx/lstm.py
modified:   keras2onnx/ke2onnx/simplernn.py
modified:   test_layers.py
```
=> Add time_major handling for bidirectional lstms

keras2onnx/_builtin.py, keras2onnx/_consts.py, keras2onnx/ke2onnx/activation.py, keras2onnx/ke2onnx/common.py, keras2onnx/ke2onnx/conv.py, keras2onnx/ke2onnx/dense.py, tests/test_layers.py
Need check in onnxconverter-common [change](https://github.com/microsoft/onnxconverter-common/pull/108) first.
=> Support tf.nn.relu6

keras2onnx/ke2onnx/activation.py, keras2onnx/ke2onnx/common.py, tests/test_layers.py
The [issue](https://github.com/onnx/keras-onnx/issues/511) cannot convert softmax activation because `operator.raw_operator.activation` is a function that is not the same as `tf.nn.softmax` or `keras.activations.get('softmax')`. We need import `tf` from `keras2onnx.proto.tfcompat`
=> Add both tf.nn.X and tf.compat.v1.nn.X to activation_map

.azure-pipelines/linux-CI-keras-applications-nightly.yml, .azure-pipelines/linux-conda-CI.yml, .azure-pipelines/win32-CI-keras-applications-nightly.yml, .azure-pipelines/win32-conda-CI.yml
keras 2.4.0 released to pypi today (6/17/2020) which installs tensorflow 2.x, then it breaks nightly build for tf 1.x case. Pin keras==2.3.1 accordingly.
=> Pin keras==2.3.1 for tensorflow 1.x in nightly build

keras2onnx/parser.py, tests/test_layers.py
See the [issue](https://github.com/onnx/keras-onnx/issues/529). Currently we just convert it using keras conversion, the problem is that keras Softmax behaves differently with onnx Softmax except axis=-1. We need swap axis with the last dim, like what it did in tensorflow.keras code.
=> Fix tf.keras.layers.Softmax conversion

applications/nightly_build/test_transformers.py
In transformers 3.0.0 in roberta models, `inputs_raw.data['input_id']` is `[None, ..., None]`, we need filter these `None`.
=> Handle None in inputs_raw.data['input_id'] for transformers 3.0.0

keras2onnx/ke2onnx/activation.py
Converting a deeplab v3 [model](https://github.com/bonlime/keras-deeplab-v3-plus). This model uses `x = Activation(tf.nn.relu)(x)`, the activation function is from tf not keras. Our original code does not consider this case. So we use `activation_map` do a further handling.
=> Convert keras activation from activation_map

applications/nightly_build/test_keras_applications_v2.py, keras2onnx/parser.py
This is to fix an error when converting an inception_resnet_v2 Keras model to ONNX:
```
AssertionError: conv_7b_bn/cond/input_0:01 is disconnected, check the parsing log for more details.
```
After investigating some background, I found inception_resnet_v2 has a name "conv_7b_bn" for a BN layer, just fixes by filtering as we do filter for "batch_normalization".
See [tensorflow/python/keras/applications/inception_resnet_v2.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/applications/inception_resnet_v2.py#L203), which defined a custom `conv_7b_bn` for a specific BN layer.
=> parser: filter the input "conv_7b_bn/cond/input"

applications/nightly_build/test_keras_applications.py, keras2onnx/common/intop.py, keras2onnx/ke2onnx/main.py, keras2onnx/ke2onnx/merge.py
Converting a ExpantionSuperResolution model [here](https://github.com/titu1994/Image-Super-Resolution). The `keras.layers.Average` has three inputs, the original code processes it progressively every two, so it will be mean(mean(A, B), C), then it is wrong. We fix it in this PR.
Also deprecate `tf2onnx_graph` in common intop.
=> Handle multiple inputs for keras.layers.Average

keras2onnx/_builtin.py, keras2onnx/_consts.py
Converting a keras-ocr model [here](https://github.com/faustomorales/keras-ocr/), and this PR helps conversion successfully.
keras-ocr ping the certain version efficientnet 1.0.0, so we are not putting into nightly build (we use latest efficientnet for testing).
=> Support tf.LinSpace and tf.AddN conversion

applications/nightly_build/test_keras_applications.py
The [PR](https://github.com/onnx/keras-onnx/pull/599) has a typo when I switch to the API `run_keras_and_ort`. This PR fixes it.
=> Typo fix for models 20200818 test

keras2onnx/_builtin.py
See the [issue](https://github.com/onnx/keras-onnx/issues/640), `diff_output` is not assigned when we don't go to `if` branch. Fix here.
=> Fix diff_output in _make_range_non_const in _builtin

keras2onnx/ke2onnx/bidirectional.py, tests/test_layers.py
In #607, it was observed that TensorFlow versions before 2.0 can have problems converting TF 2.0 compatible models because the classes are expected to be the previous API. For example in TF 1.14 the v2 compatible classes are present in `tensorflow.keras.layers.recurrent_v2`, but do not match `tensorflow.keras.layers`. This PR resolves #607 by adding support for these layers. For versions of TensorFlow that are above 2.0, this is not a problem because `tensorflow.keras.layers` uses the v2 layers.
This strategy is tested by expanding the `RNN_CLASSES` list in the tests, so that `recurrent_v2` classes are tested if present.
=> Support for recurrent_v2 layers for TF 2.0

keras2onnx/ke2onnx/main.py, tests/test_layers.py
The [PR](https://github.com/onnx/keras-onnx/pull/610) lacks the change on registering RNN recurrent_v2 conversion, so it causes linux-tf-keras-ci failure on py36 case [here](https://dev.azure.com/onnxmltools/ketone/_build/results?buildId=16396&view=logs&j=d7d66435-5ae4-561a-5876-2cd4e19b3ce2) when tensorflow==1.15.0. 
This PR fixes it. 
I also find `test_rnn_state_passing` passes for tf 2.3 locally, so enable this test in CI build.
=> Fix tf.keras CI build on RNN recurrent_v2

applications/nightly_build/test_chatbot.py, applications/nightly_build/test_crnn.py, applications/nightly_build/test_deep_rl.py, applications/nightly_build/test_efn.py, applications/nightly_build/test_keras_applications.py, applications/nightly_build/test_keras_applications_v2.py, applications/nightly_build/test_name_entity_recognition.py, applications/nightly_build/test_nbeats.py, applications/nightly_build/test_resnext.py, applications/nightly_build/test_series_net.py, applications/nightly_build/test_unet.py, applications/nightly_build/test_unet_plus_plus.py, keras2onnx/ke2onnx/upsample.py, tests/test_utils.py
Tested these two model conversions locally when I change ORT to support ConvTranspose-14.
=> Add UNetPlusPlus and UNet conversion

keras2onnx/_builtin.py, keras2onnx/ke2onnx/lstm.py, keras2onnx/ke2onnx/simplernn.py
We should set axes=[0], because Squeeze op has different meaning if we don't set axes -- it squeezes out all dimensions that has shape dim 1.
=> Set axes=[0] for apply_squeeze rather than leaving unset

requirements-dev.txt
Pillow 8.3.0 breaks the pipeline.
=> Pip install Pillow<=8.2.0
